### ISSUE TITLE
Last commit working as is?

### ISSUE THREAD

**Issue by magneto72** [abouillot/HomeAutomation#11]
Hi, i'm testing your last piGateway and base SensorNode.
Just changed frequency to 915Mhz.
I was wondering if this two programs can work without any other modifications....

in the test I'm doing, 
1. after some packets transmitted from Arduino node to the PI the arduino seems blocked and the PI tries to ping the node unsuccesfully (see picture)
2. the var2 and var3 received form PI are always 0.0000 while i set them with changing values...

is there something I Missed?
One more question: have you soldered the RFM69 NC Pin to ground as specified in the DataS.?
thanks
Gian

![pi-arduino](https://cloud.githubusercontent.com/assets/12020005/7219970/bd417dd6-e6b7-11e4-89d5-b6804d8fca67.png)

**Comment by abouillot** [comment]
I guess you made some changes in the Arduino sketch, as the time
information doesn't seem to be similar to the 3 seconds interval.

How often are you sending packet from Arduino to Pi?

**Comment by magneto72** [comment]
no modification in this test.
I see that the pi node is receiving but not able to transmit...
I saw in the RFM69HW datasheet to connect pin NC to ground....i've done it in the Arduino side but not in the PI side.... did you do that? I'll test soldering in the PI side too.

I see that if I disconnect this pin in the Arduino, the Node doesn't transmit anymore....
Regarding the power management problem with HW type in the PI side....how do you connect it?
Do you use 5v with voltage divider or directly 3V3?  Decoupling Capacitors? 
I have:
- a node with arduino 5v + voltage divider (10/20k) and RFM69 soldered even with NC to ground, powered by the PC for now; no decoupling capacitors
- RPI Model B ver2, powered by a phone charger and voltage taken at 3v3; no decoupling capacitors
  I didn't applied the power fix in rfm69.cpp done by Felix (dividing the powerlevel by 2 if HW version is used..!).
  What do you guess?

btw: transmit period: i left your code unchanged

**Comment by abouillot** [comment]
The only connections I made are the one stated in the readme https://github.com/abouillot/HomeAutomation/blob/master/piGateway/readme.md . I haven't connected any other pin. For the supply, I tested initially as shown in the same doc, but as the PI power is not sufficient to provide above 50ma, I use this power shifter from 5v to 3.3v between the Pi and RFM module: http://www.tinydeal.com/fr/ams1117-33v-power-supply-module-blue-p-100548.html .

I'm not at home for the week, so cannot check the setup, but i'm surprised the time information goes back and forth between 6 and 8, while it should be every 3000 ms so more like 3000, 6000, 9000 and so on;

**Comment by Gizzbert** [comment]
I have the setup running, also lots of time without ACK from the node, however I do get values from PIR and temp just fine from the node 2 stories down. I have wired the RFM69HW straight on the Pi GPIO's. I looked into power supply from the Pi to the 3.3v pin, and it seems that from Pi model B(+?) onward there should be enough mAmps delivered to power the RFM chip correctly (130mA+).

It occurred to me that your "time" in the screenshot above is (nearly) the same, while it should be filled with ms since start of the node. I had some weird outputs on the MQTT bus when running the Gatewayd service concurrently with running the Gateway in the console on the Pi. Easliy solved by killing the Gateway deamon process. Hope this helps.
